import type { RuntimeRoadSegment } from "@/app/lib/runtime/runtime-types";
import type { PlacedVariation } from "./types";
import { MAP_EDGE_MARGIN_M } from "./constants";
import { buildForwardRouteThroughSuccessors, worldAnchorAtFraction } from "./routing";

/**
 * Map-edge placement guard.
 *
 * Two ways an autogenerated vehicle disappears "into the abyss" on CARLA 0.10:
 *  1. Historical extracted topology can cover a larger area than the active UE5
 *     render map exports, so placements outside the measured footprint
 *     spawn-fail (belmont: bundle reaches y~1881, the 0.10 export only ~331; the
 *     DiRosa edge-despawns are the SAME root — see the 2026-07-01 plan).
 *  2. A spawn sits right on the map boundary and the vehicle drives off it.
 *
 * This gate bounds placement to a map's USABLE EXTENT. The extent is the measured
 * 0.10 footprint when the bundle over-covers it (`MAP_USABLE_EXTENT_OVERRIDES`),
 * else the bundle's own bbox. Coordinates are the runtime/frontend frame — the
 * same `world_anchor` the 0.10 worker resolves by geometry, so the gate matches
 * what the render will actually try to spawn.
 */

/** Axis-aligned usable bounds of a map in the runtime/frontend frame. */
export interface MapExtent {
  minX: number;
  maxX: number;
  minY: number;
  maxY: number;
}

/**
 * Per-map usable-extent overrides — INTERIM mirror of the source of truth, which
 * is the per-map-asset `render_extent` artifact (S3 + `map_asset_artifacts`,
 * keyed by CARLA version, e.g. `render-extents/carla-0.10.0-22.06-v3-…/<map>/`).
 * Measured with `services/carla-worker/scripts/dump_map_extents.py` (runtime
 * frame, CARLA→runtime y-flip). These values are RETIRED once the carla-bundle
 * upload workflow carries `render_extent` into the runtime bundle and
 * `resolveMapExtent` reads it from there — until then this const is the read path.
 *
 * Entries are PARTIAL-capable (merged onto the bundle bbox by `resolveMapExtent`),
 * but a full measured bbox is preferred as it bounds every direction the 0.10
 * export is smaller than the dev bundle.
 */
export const MAP_USABLE_EXTENT_OVERRIDES: Readonly<Record<string, Partial<MapExtent>>> = {
  // Measured 0.10 footprints (carla-0.10.0-22.06-v3-20260626). Belmont's dev bundle
  // anchors out to y~1881 but the 0.10 export is only [−303, 265] in y — placements
  // beyond spawn-fail "into the abyss" (2026-07-01 plan item 1).
  Belmont_Office_Park_Belmont_CA: { minX: -251.3, maxX: 233.7, minY: -303.4, maxY: 265.0 },
  Di_Rosa_SF: { minX: -127.0, maxX: 304.9, minY: -415.0, maxY: 357.9 },
};

/** Axis-aligned bbox of every segment centerline point (runtime frame); null when
 * no finite points exist (e.g. a centerline-less bundle). */
export function computeMapExtent(
  segments: Iterable<RuntimeRoadSegment>,
): MapExtent | null {
  let minX = Infinity;
  let maxX = -Infinity;
  let minY = Infinity;
  let maxY = -Infinity;
  for (const seg of segments) {
    for (const p of seg.centerline ?? []) {
      if (!Number.isFinite(p.x) || !Number.isFinite(p.y)) continue;
      if (p.x < minX) minX = p.x;
      if (p.x > maxX) maxX = p.x;
      if (p.y < minY) minY = p.y;
      if (p.y > maxY) maxY = p.y;
    }
  }
  if (!Number.isFinite(minX) || !Number.isFinite(minY)) return null;
  return { minX, maxX, minY, maxY };
}

/**
 * The usable extent for a map, in priority order:
 *   1. `renderExtent` — the measured 0.10 footprint from the map-asset
 *      `render_extent` artifact (source of truth; fetched by the caller, see
 *      `extent-source.ts`).
 *   2. the interim const `MAP_USABLE_EXTENT_OVERRIDES` merged onto the bundle bbox
 *      (fallback for maps whose artifact fetch missed).
 *   3. the bundle bbox alone.
 *   4. null → the guard is a no-op (worker's geometry-anchor guard backstops).
 *
 * `renderExtent` is passed already-fetched so this stays pure + synchronously
 * unit-testable; the DB/S3 read lives in `fetchMapRenderExtent`.
 */
export function resolveMapExtent(
  mapName: string,
  segments: Iterable<RuntimeRoadSegment>,
  renderExtent?: MapExtent | null,
): MapExtent | null {
  if (renderExtent) return renderExtent;
  const bbox = computeMapExtent(segments);
  const override = MAP_USABLE_EXTENT_OVERRIDES[mapName];
  if (!override) return bbox;
  const merged = { ...(bbox ?? {}), ...override };
  const complete =
    Number.isFinite(merged.minX) &&
    Number.isFinite(merged.maxX) &&
    Number.isFinite(merged.minY) &&
    Number.isFinite(merged.maxY);
  return complete ? (merged as MapExtent) : bbox;
}

/** Parse a `render_extent` artifact's JSON body into a MapExtent (runtime frame).
 * Returns null if the shape is missing/invalid — the caller then falls back. */
export function parseRenderExtentArtifact(text: string): MapExtent | null {
  let doc: unknown;
  try {
    doc = JSON.parse(text);
  } catch {
    return null;
  }
  const e = (doc as { usable_extent?: unknown })?.usable_extent as
    | Partial<MapExtent>
    | undefined;
  if (!e) return null;
  const { minX, maxX, minY, maxY } = e;
  if (
    !Number.isFinite(minX) ||
    !Number.isFinite(maxX) ||
    !Number.isFinite(minY) ||
    !Number.isFinite(maxY)
  ) {
    return null;
  }
  return { minX, maxX, minY, maxY } as MapExtent;
}

/** Pick the `render_extent` artifact for the target render runtime. Prefers an
 * artifact whose key matches `preferVersion` (e.g. `carla-0.10`); else the newest
 * by embedded version string. Null if the map has no render_extent artifact. */
export function pickRenderExtentArtifact<T extends { artifact_type: string; uri: string }>(
  artifacts: readonly T[],
  preferVersion?: string,
): T | null {
  const cands = artifacts.filter((a) => a.artifact_type === "render_extent");
  if (cands.length === 0) return null;
  if (preferVersion) {
    const match = cands.find((a) => a.uri.includes(preferVersion));
    if (match) return match;
  }
  // Newest by embedded CARLA version, compared NUMERICALLY per segment —
  // lexicographic URI ordering ranks carla-0.9 above carla-0.10 ("9" > "1"),
  // which would hand a 0.10 render a 0.9 extent when the preferred prefix
  // doesn't match (PR #309 review). Versionless URIs sort last.
  const versionKey = (uri: string): number[] => {
    const m = /carla-(\d+(?:\.\d+)*)/.exec(uri);
    return m ? m[1]!.split(".").map(Number) : [-1];
  };
  const cmp = (a: number[], b: number[]): number => {
    for (let i = 0; i < Math.max(a.length, b.length); i += 1) {
      const d = (a[i] ?? 0) - (b[i] ?? 0);
      if (d !== 0) return d;
    }
    return 0;
  };
  return [...cands].sort(
    (a, b) => cmp(versionKey(b.uri), versionKey(a.uri)) || b.uri.localeCompare(a.uri),
  )[0]!;
}

function withinExtent(
  point: { x: number; y: number },
  extent: MapExtent,
  margin: number,
): boolean {
  return (
    point.x >= extent.minX + margin &&
    point.x <= extent.maxX - margin &&
    point.y >= extent.minY + margin &&
    point.y <= extent.maxY - margin
  );
}

/**
 * True if the placement's spawn is safely inside the map's usable extent. Rejects
 * when the spawn sits within `edgeMargin` of the boundary, OR when the spawn lane
 * EXITS the usable extent (leads off the covered map). No-op (true) when no extent
 * or no finite spawn position is available — the worker's geometry-anchor guard is
 * the render-time backstop.
 */
export function placementWithinExtent(
  placed: PlacedVariation,
  extent: MapExtent | null,
  edgeMargin: number = MAP_EDGE_MARGIN_M,
): boolean {
  if (!extent) return true;
  const spawn = worldAnchorAtFraction(placed.spawnSegment, placed.variation.spawnFraction);
  if (!spawn) return true;
  if (!withinExtent(spawn, extent, edgeMargin)) return false;
  // The lane the subject immediately drives onto must not lead off the covered map:
  // its far end (fraction 1) must be inside the hard extent. This is a no-op under
  // the bundle-bbox fallback (a bundle lane's end is inside the bundle by
  // definition) but catches lanes that CROSS a 0.10-override boundary.
  const exit = worldAnchorAtFraction(placed.spawnSegment, 1);
  if (exit && !withinExtent(exit, extent, 0)) return false;
  return true;
}

/**
 * Stricter guard for maneuvers that drive a long FORWARD corridor before the label
 * lands — lane changes and overtakes. placementWithinExtent only checks the spawn +
 * its own lane end, so a spawn just inside the boundary whose forward pass corridor
 * runs off the covered map still passed (the overtake subject + traffic "disappearing at
 * the edge of the map", dib 2026-07-09). Walk the subject's forward route through
 * successors for `forwardMeters` and require EVERY sampled point to stay inside the
 * hard extent. No-op when no extent is available.
 */
export function corridorWithinExtent(
  segments: ReadonlyMap<string, RuntimeRoadSegment>,
  placed: PlacedVariation,
  extent: MapExtent | null,
  forwardMeters: number,
): boolean {
  if (!extent) return true;
  const route = buildForwardRouteThroughSuccessors(
    segments,
    placed.spawnSegment,
    placed.variation.spawnFraction,
    placed.variation.speedKph,
    forwardMeters,
  );
  for (const anchor of route) {
    const w = anchor.world_anchor;
    if (w && !withinExtent(w, extent, 0)) return false;
  }
  return true;
}
