import type { BridgedMapBundle, MapLocation } from "@/app/lib/editor-map/types";
import type { EditorToolContext } from "./types";

const FIXTURE_LOCATION: MapLocation = {
  id: "loc-1",
  source: "simcloud_candidate",
  kind: "junction",
  classification: "four_way",
  label: "Main & First",
  description: "Signalized four-way intersection",
  bridge: "guid",
  road_ids: ["10", "11"],
  road_count: 2,
  bounds: {
    minX: 0,
    minY: -50,
    maxX: 100,
    maxY: 50,
    width: 100,
    height: 100,
  },
  center: { x: 50, y: 0 },
  tags: ["INTERSECTION_SIGNALIZED"],
  evidence: [],
  feature_flags: {
    has_stop_control: false,
    has_crosswalk: true,
    has_traffic_light: true,
    has_parking: false,
    has_sidewalk: true,
    has_bike_lane: false,
    road_markings: ["stop_line"],
    signal_categories: ["traffic_light"],
  },
  approaches: [
    {
      road_id: "10",
      name: "Main Street",
      bearing: "eastbound",
      lane_config: "1+1",
      lane_types: ["driving"],
      length_m: 100,
    },
    {
      road_id: "11",
      name: "First Avenue",
      bearing: "northbound",
      lane_config: "1+1",
      lane_types: ["driving"],
      length_m: 100,
    },
  ],
  junction_id: "J1",
  related_lane_guids: [],
  related_feature_ids: [],
  related_road_names: ["Main Street", "First Avenue"],
};

export function buildEditorToolFixtureBundle(): BridgedMapBundle {
  return {
    asset: {
      map_asset_id: "fixture-map",
      name: "Fixture Map",
      carla_map_name: "Fixture_Map",
      crs: "EPSG:4326",
      bbox: {
        min_lat: 36.999,
        min_lng: -122.001,
        max_lat: 37.001,
        max_lng: -121.999,
      },
      center: { lat: 37, lng: -122 },
      created_at: "2026-01-01T00:00:00.000Z",
      artifacts: [],
      map_coordinate_ref: {
        origin_lat: 37,
        origin_lon: -122,
      },
    },
    bundle_version: "fixture-bundle",
    runtime_bundle_key: "map-bundles/fixture-bundle/Fixture_Map/bundle.json",
    candidate_locations: [],
    enrichment: null,
    geojson: { type: "FeatureCollection", features: [] },
    geojson_url: null,
    signals_geojson: null,
    generated: {
      name: "Fixture Map",
      fileName: "fixture-map.xodr",
      optimized: true,
      bounds: {
        minX: 0,
        minY: -50,
        maxX: 100,
        maxY: 50,
        width: 100,
        height: 100,
      },
      stats: {
        roads: 2,
        junctionDefinitions: 1,
        laneTypes: { driving: 2 },
        featureCounts: {
          intersection: 1,
          parking: 0,
          single_lane_road: 0,
          single_lane_each_way: 0,
          two_lane_one_way: 0,
          two_lane_each_way: 0,
          crosswalk: 1,
          stop_control: 0,
        },
      },
      roads: [
        {
          id: "10",
          name: "Main Street",
          junctionId: "J1",
          isIntersection: false,
          length: 100,
          path: "M 0 0 L 100 0",
          surface: "",
          drivingSurface: "",
          laneLines: [],
          bounds: {
            minX: 0,
            minY: 0,
            maxX: 100,
            maxY: 0,
            width: 100,
            height: 0,
          },
          tags: [],
          sections: [
            {
              index: 0,
              label: "Section 0",
              s: 0,
              drivingLeft: 0,
              drivingRight: 1,
              parkingLeft: 0,
              parkingRight: 0,
              totalDriving: 1,
              totalWidth: 3.5,
              laneTypes: ["driving"],
              tags: [],
            },
          ],
          objects: [],
        },
        {
          id: "11",
          name: "First Avenue",
          junctionId: "J1",
          isIntersection: false,
          length: 100,
          path: "M 100 -50 L 100 50",
          surface: "",
          drivingSurface: "",
          laneLines: [],
          bounds: {
            minX: 100,
            minY: -50,
            maxX: 100,
            maxY: 50,
            width: 0,
            height: 100,
          },
          tags: [],
          sections: [
            {
              index: 0,
              label: "Section 0",
              s: 0,
              drivingLeft: 0,
              drivingRight: 1,
              parkingLeft: 0,
              parkingRight: 0,
              totalDriving: 1,
              totalWidth: 3.5,
              laneTypes: ["driving"],
              tags: [],
            },
          ],
          objects: [],
        },
      ],
      crosswalks: [],
      stopMarkers: [],
    },
    runtime: {
      map_name: "Fixture_Map",
      normalized_map_name: "Fixture_Map",
      road_summaries: [
        {
          id: "10",
          name: "Main Street",
          is_intersection: false,
          tags: [],
          lane_types: ["driving"],
          has_parking: false,
          has_shoulder: false,
          has_sidewalk: true,
          section_summaries: [],
        },
        {
          id: "11",
          name: "First Avenue",
          is_intersection: false,
          tags: [],
          lane_types: ["driving"],
          has_parking: false,
          has_shoulder: false,
          has_sidewalk: true,
          section_summaries: [],
        },
      ],
    },
    xodr: null,
    street_furniture: null,
    locations: [FIXTURE_LOCATION],
    bridge_summary: {
      lane_guid_count: 0,
      candidate_location_count: 1,
      derived_location_count: 1,
    },
    carla_status: {
      connected: true,
      current_map: "Fixture_Map",
      normalized_map_name: "Fixture_Map",
      server_version: null,
      client_version: null,
      available_maps: [],
      warnings: [],
    },
    map_match: true,
  };
}

export function buildEditorToolFixtureContext(): EditorToolContext {
  const bundle = buildEditorToolFixtureBundle();
  return {
    mapAssetId: bundle.asset.map_asset_id,
    bundle,
    selectedRoadIds: ["10"],
    selectedLocation: bundle.locations[0] ?? null,
  };
}
